# Generated by Django 5.2.7 on 2026-03-13 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_postmedia_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmedia',
            name='original_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
